[INFO 22:49:03] pymarl Running command 'my_main'
[INFO 22:49:03] pymarl Started run with ID "11"
[DEBUG 22:49:03] pymarl Starting Heartbeat
[DEBUG 22:49:03] my_main Started
[WARNING 22:49:03] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
[INFO 22:49:03] my_main Experiment Parameters:
[INFO 22:49:03] my_main 

{   'action_selector': 'soft_policies',
    'add_value_last_step': True,
    'agent': 'rnn',
    'agent_output_type': 'pi_logits',
    'batch_size': 10,
    'batch_size_run': 10,
    'buffer_cpu_only': True,
    'buffer_size': 10,
    'checkpoint_path': '',
    'common_reward': False,
    'critic_type': 'cv_critic',
    'entropy_coef': 0.001,
    'env': 'gymma',
    'env_args': {   'key': 'rware:rware-tiny-4ag-v2',
                    'pretrained_wrapper': None,
                    'seed': 3514159,
                    'time_limit': 50},
    'epochs': 4,
    'eps_clip': 0.2,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hidden_dim': 128,
    'hypergroup': None,
    'label': 'default_label',
    'learner': 'ppo_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 50000,
    'lr': 0.0003,
    'mac': 'basic_mac',
    'mask_before_softmax': True,
    'name': 'mappo',
    'obs_agent_id': True,
    'obs_individual_obs': False,
    'obs_last_action': False,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'q_nstep': 5,
    'render': False,
    'repeat_id': 1,
    'reward_scalarisation': 'sum',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'save_model': True,
    'save_model_interval': 50000,
    'save_replay': False,
    'seed': 3514159,
    'standardise_returns': False,
    'standardise_rewards': True,
    't_max': 5000000,
    'target_update_interval_or_tau': 0.01,
    'test_greedy': True,
    'test_interval': 50000,
    'test_nepisode': 100,
    'use_cuda': False,
    'use_rnn': True,
    'use_tensorboard': False,
    'use_wandb': True,
    'wandb_mode': 'online',
    'wandb_project': 'rware-mappo',
    'wandb_save_model': True,
    'wandb_team': 'university_of_calgary'}

[DEBUG 22:49:03] wandb.docker.auth Trying paths: ['/home/ubuntu/.docker/config.json', '/home/ubuntu/.dockercfg']
[DEBUG 22:49:03] wandb.docker.auth No config file found
[DEBUG 22:49:03] git.cmd Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware, stdin=None, shell=False, universal_newlines=False)
[DEBUG 22:49:03] git.cmd Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware, stdin=None, shell=False, universal_newlines=False)
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
[DEBUG 22:49:04] urllib3.connectionpool Starting new HTTPS connection (1): api.wandb.ai:443
[DEBUG 22:49:04] urllib3.connectionpool https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 None
[DEBUG 22:49:04] urllib3.connectionpool https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 None
wandb: Currently logged in as: mobina-jamali-mj (university_of_calgary). Use `wandb login --relogin` to force relogin
[DEBUG 22:49:04] git.cmd Popen(['git', 'cat-file', '--batch-check'], cwd=/home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware, stdin=<valid stream>, shell=False, universal_newlines=False)
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in /home/ubuntu/PERSONAL-DIR/UOA-NEW/human-rware/wandb/run-20241105_224904-cf0uaaca
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run atomic-firebrand-24
wandb: ‚≠êÔ∏è View project at https://wandb.ai/university_of_calgary/rware-mappo
wandb: üöÄ View run at https://wandb.ai/university_of_calgary/rware-mappo/runs/cf0uaaca
[INFO 22:49:04] my_main *******************
[INFO 22:49:04] my_main WANDB RUN ID:
[INFO 22:49:04] my_main cf0uaaca
[INFO 22:49:04] my_main *******************
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:265: UserWarning: [33mWARN: Human rendering should return `None`, got <class 'bool'>[0m
  logger.warn(
	Done: False
/home/ubuntu/miniconda3/envs/epymarl/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:245: UserWarning: [33mWARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'list'>[0m
  logger.warn(
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
	Done: False
